# Generic script.py.mako
"""add images and has_lift columns

Revision ID: 0043b5cfbae4
Revises: eab2a75e6f73
Create Date: 2026-06-02 21:43:11.583980+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0043b5cfbae4'
down_revision: Union[str, None] = 'eab2a75e6f73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('has_lift', sa.Boolean(), nullable=True))
    op.add_column('listings', sa.Column('images', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listings', 'images')
    op.drop_column('listings', 'has_lift')
    # ### end Alembic commands ###
