# Generic script.py.mako
"""Add match_id to notifications

Revision ID: eab2a75e6f73
Revises: 6a56030099e4
Create Date: 2026-06-02 13:11:48.526995+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eab2a75e6f73'
down_revision: Union[str, None] = '6a56030099e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('match_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_notifications_match_id'), 'notifications', ['match_id'], unique=False)
    op.create_foreign_key(None, 'notifications', 'matches', ['match_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_index(op.f('ix_notifications_match_id'), table_name='notifications')
    op.drop_column('notifications', 'match_id')
    # ### end Alembic commands ###
