# Generic script.py.mako
"""Initial schema

Revision ID: 6a56030099e4
Revises: 
Create Date: 2026-06-02 13:02:00.357604+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6a56030099e4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=200), nullable=True),
    sa.Column('neighborhood', sa.String(length=200), nullable=True),
    sa.Column('address_text', sa.Text(), nullable=True),
    sa.Column('rental_type', sa.Enum('APARTMENT', 'ROOM', 'BOTH', 'UNKNOWN', name='listing_rental_type_enum'), nullable=False),
    sa.Column('area_m2', sa.Float(), nullable=True),
    sa.Column('rooms', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Integer(), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('has_elevator', sa.Boolean(), nullable=True),
    sa.Column('is_furnished', sa.Boolean(), nullable=True),
    sa.Column('agency_or_private', sa.String(length=50), nullable=True),
    sa.Column('available_from', sa.String(length=100), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'REMOVED', 'UNKNOWN', name='listing_status_enum'), nullable=False),
    sa.Column('dedup_hash', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listings_dedup_hash'), 'listings', ['dedup_hash'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('language', sa.Enum('EN', 'RU', name='language_enum'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'DELETED', name='user_status_enum'), nullable=False),
    sa.Column('plan', sa.Enum('FREE', 'BETA', 'PRO', name='user_plan_enum'), nullable=False),
    sa.Column('consent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('feedback_type', sa.Enum('USEFUL', 'NOT_RELEVANT', 'SUSPICIOUS', 'CONTACTED', 'HIDE_SIMILAR', name='feedback_type_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_listing_id'), 'feedback', ['listing_id'], unique=False)
    op.create_index(op.f('ix_feedback_user_id'), 'feedback', ['user_id'], unique=False)
    op.create_table('listing_analysis',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('summary_en', sa.Text(), nullable=True),
    sa.Column('summary_ru', sa.Text(), nullable=True),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='risk_level_enum'), nullable=True),
    sa.Column('red_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('positive_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('questions_to_ask', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('contract_type', sa.Enum('LONG_TERM', 'TEMPORADA', 'UNKNOWN', name='contract_type_enum'), nullable=True),
    sa.Column('empadronamiento_possible', sa.Enum('YES', 'NO', 'UNKNOWN', name='empadronamiento_enum'), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('analysis_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listing_analysis_listing_id'), 'listing_analysis', ['listing_id'], unique=True)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('telegram_message_id', sa.BigInteger(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('SENT', 'FAILED', 'PENDING', name='notification_status_enum'), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_listing_id'), 'notifications', ['listing_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('user_searches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('rental_type', sa.Enum('APARTMENT', 'ROOM', 'BOTH', 'UNKNOWN', name='rental_type_enum'), nullable=False),
    sa.Column('min_price', sa.Float(), nullable=True),
    sa.Column('max_price', sa.Float(), nullable=True),
    sa.Column('min_rooms', sa.Integer(), nullable=True),
    sa.Column('preferred_areas', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('excluded_areas', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('must_have', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('nice_to_have', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_searches_user_id'), 'user_searches', ['user_id'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('search_id', sa.Integer(), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('reason_en', sa.Text(), nullable=True),
    sa.Column('reason_ru', sa.Text(), nullable=True),
    sa.Column('should_notify', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['search_id'], ['user_searches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'listing_id', name='uq_match_user_listing')
    )
    op.create_index(op.f('ix_matches_listing_id'), 'matches', ['listing_id'], unique=False)
    op.create_index(op.f('ix_matches_user_id'), 'matches', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_matches_user_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_listing_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_user_searches_user_id'), table_name='user_searches')
    op.drop_table('user_searches')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_listing_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_listing_analysis_listing_id'), table_name='listing_analysis')
    op.drop_table('listing_analysis')
    op.drop_index(op.f('ix_feedback_user_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_listing_id'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_listings_dedup_hash'), table_name='listings')
    op.drop_table('listings')
    # ### end Alembic commands ###
