# Generic script.py.mako
"""add unique constraint on external_id and source

Revision ID: 96ddd44f3f8b
Revises: fd453ad67bfe
Create Date: 2026-06-02 21:54:24.158705+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96ddd44f3f8b'
down_revision: Union[str, None] = 'fd453ad67bfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_listing_external_source', 'listings', ['external_id', 'source'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_listing_external_source', 'listings', type_='unique')
    # ### end Alembic commands ###
