# Generic script.py.mako
"""expand rental types

Revision ID: fd453ad67bfe
Revises: 0043b5cfbae4
Create Date: 2026-06-02 21:48:18.892731+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd453ad67bfe'
down_revision: Union[str, None] = '0043b5cfbae4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
